[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor --chip esp32"

[env]
OPUS_LIB_DIR = "/Users/astrick/Repositories/chatbot-rs/firmware/lib"

[build]
rustflags = ["-C", "link-arg=-nostartfiles"]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["core", "alloc"]
